{% raw -%}
- name: Setup directory permissions for all
  file:
    path: "{{ ansistrano_deploy_to }}/"
    state: directory
    mode: 0775
    owner: www-data
    group: www-data
    recurse: true
    follow: yes
- name: Setup directory permissions for uploads
  file:
    path: "{{ ansistrano_shared_path }}/src/app/uploads"
    state: directory
    mode: 0775
    owner: www-data
    group: www-data
    recurse: true
    follow: yes

- name: Make sure www-data:www-data has ownership of current
  file:
    path: "{{ item }}"
    owner: www-data
    group: www-data
    state: directory
    recurse: yes
  with_items:
    - "{{ ansistrano_deploy_to }}/current"
 {% endraw %}